# Generated by Django 2.2.6 on 2019-10-10 19:01

from uuid import uuid4

from django.db import migrations


def apply_migration(apps, migration):
    """Apply App Token data migration"""
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(
        name='App Token'
    )


def revert_migration(apps, migration):
    """Revert App Token data migration"""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name='App Token'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
