# Generated by Django 2.2.6 on 2019-10-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twix', '0002_auto_20191019_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='twix.Group'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
